#!/bin/sh
#
# Basic tests to ensure adding datasets to a DD in JCL works
#

. zospmsetenv

jcl="//STEP1 EXEC PGM=IEFBR14
//MYDD DD DSN=MY.TEST.DATASET,DISP=SHR
//     DD DSN=ANOTHER.TEST.DATASET,DISP=SHR
//*
//     DD DISP=SHR,THIRD.DATASET
//*
//SYSUT1 DD SYSOUT=*
//*
//STEP2 EXEC PGM=FREELOAD,PARM='SOME PARM'
//STDOUT DD DISP=OLD,MY.OUTPUT
//SYSIN DD
 Here
 is 
 Text   
/*
//STEP3 EXEC PGM=LAST
//STDOUT DD SYSOUT=*
//MYOUT  DD DSN=FRED.JACK,DISP=SHR
//SYSIN  DD DSN=MY.MAGIC.FILE,DISP=SHR"

jclMyDDAdd="//STEP1 EXEC PGM=IEFBR14
//MYDD DD DSN=ZOSPM.MYDD.DATASET,DISP=SHR
// DD DSN=MY.TEST.DATASET,DISP=SHR
//     DD DSN=ANOTHER.TEST.DATASET,DISP=SHR
//*
//     DD DISP=SHR,THIRD.DATASET
//*
//SYSUT1 DD SYSOUT=*
//*
//STEP2 EXEC PGM=FREELOAD,PARM='SOME PARM'
//STDOUT DD DISP=OLD,MY.OUTPUT
//SYSIN DD
 Here
 is 
 Text   
/*
//STEP3 EXEC PGM=LAST
//STDOUT DD SYSOUT=*
//MYOUT  DD DSN=FRED.JACK,DISP=SHR
//SYSIN  DD DSN=MY.MAGIC.FILE,DISP=SHR"

jclSYSINAdd="//STEP1 EXEC PGM=IEFBR14
//MYDD DD DSN=MY.TEST.DATASET,DISP=SHR
//     DD DSN=ANOTHER.TEST.DATASET,DISP=SHR
//*
//     DD DISP=SHR,THIRD.DATASET
//*
//SYSUT1 DD SYSOUT=*
//*
//STEP2 EXEC PGM=FREELOAD,PARM='SOME PARM'
//STDOUT DD DISP=OLD,MY.OUTPUT
//SYSIN DD
 Here
 is 
 Text   
/*
//STEP3 EXEC PGM=LAST
//STDOUT DD SYSOUT=*
//MYOUT  DD DSN=FRED.JACK,DISP=SHR
//SYSIN DD DSN=ZOSPM.MYSYSIN.DATASET,DISP=SHR
//  DD DSN=MY.MAGIC.FILE,DISP=SHR"

jclStdoutAdd="//STEP1 EXEC PGM=IEFBR14
//MYDD DD DSN=MY.TEST.DATASET,DISP=SHR
//     DD DSN=ANOTHER.TEST.DATASET,DISP=SHR
//*
//     DD DISP=SHR,THIRD.DATASET
//*
//SYSUT1 DD SYSOUT=*
//*
//STEP2 EXEC PGM=FREELOAD,PARM='SOME PARM'
//STDOUT DD DSN=ZOSPM.MYSTDOUT.DATASET,DISP=SHR
// DD DISP=OLD,MY.OUTPUT
//SYSIN DD
 Here
 is 
 Text   
/*
//STEP3 EXEC PGM=LAST
//STDOUT DD SYSOUT=*
//MYOUT  DD DSN=FRED.JACK,DISP=SHR
//SYSIN  DD DSN=MY.MAGIC.FILE,DISP=SHR"

actual=`jclAddDatasetToDD "${jcl}" "STEP1" "MYDD" "ZOSPM.MYDD.DATASET"`
zospmtest "jclAddDatasetToDD failed for STEP1.MYDD" "0" "$?" 
zospmtest "jclAddDatasetToDD failed for STEP1.MYDD" "${jclMyDDAdd}" "${actual}"

actual=`jclAddDatasetToDD "${jcl}" "STEP3" "SYSIN" "ZOSPM.MYSYSIN.DATASET"`
zospmtest "jclAddDatasetToDD failed for STEP1.MYSYSIN" "0" "$?" 
zospmtest "jclAddDatasetToDD failed for STEP1.MYSYSIN" "${jclSYSINAdd}" "${actual}"

actual=`jclAddDatasetToDD "${jcl}" "STEP2" "STDOUT" "ZOSPM.MYSTDOUT.DATASET"`
zospmtest "jclAddDatasetToDD failed for STEP2.MYSTDOUT" "0" "$?" 
zospmtest "jclAddDatasetToDD failed for STEP2.MYSTDOUT" "${jclStdoutAdd}" "${actual}"


exit 0
