#!/bin/sh
if [ $# != 2 ]; then
	echo "smplstzones <csi>"
	exit 4
fi
out=$(whence zospminternalfuncs >/dev/null)
if [ $? -eq 0 ]; then
	. zospminternalfuncs
else    	
	echo "zospm tools need to be in your PATH" >&2
	exit 4
fi
out=$(whence zospmexternalfuncs >/dev/null)
if [ $? -eq 0 ]; then
	. zospmexternalfuncs
else    	
	echo "zospm tools need to be in your PATH" >&2
	exit 4
fi

mydir=$(callerdir ${0})
props="${mydir}/../zospmglobalprops.json"
zospmpropse zospm config "${props}"

csi="$(echo ${1} | tr '[:lower:]' '[:upper:]')"

tmpCntlHFS=${ZOSPM_TMP}/$$.${tgtzone}.zonecntl.xml
zonelist=${ZOSPM_TMP}/$$.${tgtzone}.zonesmp.zonelst
touch ${zonelist}

echo "  SET BOUNDARY(GLOBAL).
  LIST GZONE.
" >${tmpCntlHFS}

smpout=`smp -i ${csi} -l ${zonelist} <${tmpCntlHFS}`
rc=$?
if [ $rc -eq 0 ]; then
	tgtzones=`awk '{ if (NF==3 && $2=="TARGET") { print($1); } }' < ${zonelist}`
	rm -rf ${zonelist} ${tmpCntlHFS}
	echo "${tgtzones}"
else
	echo "${smpout}" >&2
fi
exit $rc
